### ISSUE TITLE
Create Seed data for Development project

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#205]
# Expected Behaviour

Now that the Development Environment has been set up with a local copy of the Database all contributors will be working with a fixed set of data on their local repo. That data should be planned out to help us test fringe cases and drive the development process. For example, conversations should include:

> - a conversation that relates to an item that has been deleted
> - a conversation where no messages have yet been exchanged
> - a conversation where the latest message from the other person has not yet been read
> - etc...

> There should also probably be a test user that we provide the credentials for in our documentation 🤔 

## Updated

The seed file on our codebase should outline a controlled set of data that can allow developers to test out several cases during the development of Kindly. This should include:

- A `Test Donor` and a `Test Refugee` accounts that we can share the log in details for to new contributors
- Four to five items uploaded by each of the test users
  - The uploaded items should be of different categories and include images of different file formats and sizes
- There should be ongoing conversations between the two test users
  - At least one conversation should have no messages exchanged by the users
  - At least one conversation should have an unread message that's been sent by the donor
  - At least one conversation should have an unread message that's been sent by the refugee
  - At least one conversation should relate to an item that has been deleted by the donor since the conversation started
  - At least one conversation should have several messages exchanged between the users over the span of a few different days

If we provide a set of data like this to every developer we can guarantee a controlled environment where different use cases can be tested as we built upon the current features of Kindly 

# Current Behaviour

The seed file currently populates the local database with a copy of the data that was available in our project at the time when the new environment was set up (email addresses and names were replaced with dummy data) which leaves us with an uncontrolled data set.

## Steps to Reproduce

Follow the guidance in `BEFORE_YOUR_FIRST_ISSUE.md` on setting up a local copy of the database. Once you have set everything up and your local environment has been seeded you will have a snapshot of the data that was on our staging database a few weeks ago.

**Comment by camelPhonso** [comment]
@KkageG @eagauss - could either one of you or either of the other QA's spare some time to this issue? 

There is a `seed.sql` file where we set up the data to be seeded but I ran into trouble when I tried to manually create this due to having to deal with auth tables in our project. The supabase docs also suggest a package called [snaplet](https://supabase.com/docs/guides/cli/seeding-your-database#generating-seed-data) but I hit a wall there as well 😞 

I'm hoping this is right up your alley 🤞

**Comment by eagauss** [comment]
@camelPhonso I have gone through the Supabase docs but still did not get how to connect to it to see the database structure.
Could you help me with that?
It will help me see the database structure and either try to create the seed.sql file manually or generate it with the package you mentioned.

**Comment by camelPhonso** [comment]
> [@camelPhonso](https://github.com/camelPhonso) I have gone through the Supabase docs but still did not get how to connect to it. Yeah, there are credentials in the .env file but it's not very helpful. Could you help me with that? It will help me see the database structure and either try to create the seed.sql file manually or generate it with the package you mentioned.

Hey @eagauss once you have followed the set up on `before_your_first_issue.md` you should be able to get the `Studio URL` value on your terminal by entering the command `supabase status`. That value is the url of the supabase console for your local environment, where you can see the database structure.

There is also a `seed.sql` file inside the supabase directory in the codebase that you can review.

**Comment by eagauss** [comment]
Hey @camelPhonso 
I got the database running locally a couple days ago and went through the supabase as well as the snaplet docs but no luck so far.

Yeah, the task is open for contributions.
Still, from my perspective, it would be beneficial to see what exactly you want to achieve.

I mean, the seed.sql file with some data already exists and it is not very clear what exactly you want to have in a new seed.sql file or in the snaplet script to create it.

The last idea I came up with was to create some test data on the UI and just dump the database and clean up the dump.sql file manually.

**Comment by camelPhonso** [comment]
> Yeah, the task is open for contributions. Still, from my perspective, it would be beneficial to see what exactly you want to achieve.
 
> The last idea I came up with was to create some test data on the UI and just dump the database and clean up the dump.sql file manually.

Thanks @eagauss - that may well end up being how we go about it. I'll look to create an outline of a few cases the seed data should contain and will post in this issue 💡

**Comment by camelPhonso** [comment]
Updated the original description of this issue and added the `help wanted` label as I'm hoping someone might have an input on usual practices for replicating what we want to get out of this issue

**Comment by mnixo** [comment]
Hey! I was checking out this issue and there are a few things that might be worth checking out.

`supabase db dump` ([doc](https://supabase.com/docs/reference/cli/supabase-db-dump)) could be really useful here:
- Using `--local` will make sure you're targeting your running local instance.
- By default, the command will output the current schema of the database. By using `--data-only`, it'll dump all the data records, so essentially the same content that you currently have in `seed.sql` ([link](https://github.com/enBloc-org/kindly/blob/19a00ec10861752ad9b42629008241b537e873aa/supabase/seed.sql)).
- `--exclude` is also pretty nice to avoid dumping any table data that is not particularly relevant for the seed of a local instance.

If I understand correctly, the goal is to set up the seed file so that when the local Supabase instance is started it reflects an app state with several different scenarios for testing/validation. I think this can be achieved by starting a fresh Supabase instance with the current seed, do whatever necessary set up that needs to be done manually (creating users, items, conversations, etc.) and running `supabase db dump --data-only --file supabase/seed.sql` at the end. This should override the existing seed file with the data on the instance (current seed data + new fringe scenario set up data).

On a secondary note, I would suggest trimming the current seed file a little bit. At 53.658 lines (~15MB), it's pretty big. The good thing is that most of that (~50k lines) is just data from `auth.audit_log_entries`, a table that I'm not seeing being used anywhere in the app's source code (worth double checking, though). I couldn't find any official documentation on it, but I would assume that tables like these are used by Supabase for it's built-in auditing capabilities (PGAudit?), so nothing necessary in this context (presumably). If so, could be `--exclude`'d during the dump.

It might be possible to start "fresh" by replacing the existing migration files with a single schema file (the result of `supabase db dump --local`, without the `--data-only`) and with a brand new seed file without any of the existing data. Running a few migration scripts on a new local instance doesn't seem necessary. Of course, the set up would have to accommodate any other data that is necessary for the app to operate ([like the user that you need to have in the database in order to be able to send a message on an item!](https://github.com/enBloc-org/kindly/blob/a5e1b953ccc9c0cf5afac08e0b0a9285b0cae42b/supabase/models/messaging/selectSystemUser.ts#L13)). But again, this would be a complementary nice-to-have.

Please let me know if there's anything you want me to try here. If we agree on something, I'd be willing to put a PR together!

**Comment by camelPhonso** [comment]
Thanks @mnixo 🙌 

We used `db dump` for the original setup actually. There are a few things to add context here:

- we want the setup to be exactly the same when any collaborators start their local environment so we can perform controlled tests
  - for this reason we chose to have a `seed.sql` file instead of performing a `db dump` for each new instance
- the `auth` table is used in the background to create a profile for each new user
  - this table is also used for our notification system in the background so it may cause unexpected behaviour if missing from our local
  - however, the `auth.audit_log_entries` should not need to have any records for the local environment
- some functionality happens in `supabase` and is not visible in the codebase, which is why migrations files have slowly been added to track new changes to the schema and bring version control to this aspect of Kindly
  - this solution is far from perfect and up for review, but for now I think it's something we want to keep doing

This is the plan I make out from your notes:
1. perform a dump of the schema without any data - (here we could delete current migration files as we'd "rebase" the schema)
2. manually create new data in the local environment
3. dump the new data into a `seed.sql` file

@eagauss  I've suggested originally that one of the QA's handle this as the seed data should be taken into account for our automated tests going forward but if you'd like to get the extra pair of hands to help with the set up feel free to organise with @mnixo - I'm not aware how far you've gotten into planning for this so I leave it up to your call but the plan seems sound

**Comment by eagauss** [comment]
@mnixo @camelPhonso 
I have just created test data on empty database locally and dumped it.
Please have a look
#263

**Comment by eagauss** [comment]
There are two users:
`donor+test.reshetniak@gmail.com`
`refugee+test.reshetniak@gmail.com`
The password:
`schemu8s`
And test data as requested:
- One conversation should have no messages exchanged by the users
- One conversation should have an unread message that's been sent by the donor
- One conversation should have an unread message that's been sent by the refugee
- One conversation should relate to an item that has been deleted by the donor since the conversation started
- One conversation should have several messages exchanged between the users over the span of a few different days

I ran commands:
`supabase start`
`supabase db reset`
to re-seed the database with new data.

Everything seems to be fine apart from the broken userpics and product thumbnails.

**Comment by mnixo** [comment]
I checked out the branch and started supabase and the app without issues.
I was able to login and browse with both users. Besides the missing images, everything seemed to work fine and I could see a few pre-populated items and conversations. I didn't validate if all the uses cases specified in this issue are set up, though.

The seed file is now way smaller and way manageable. Great job!

**Comment by camelPhonso** [comment]
Following a review of @eagauss's PR a different problem that had recently been pointed out by another contributor has been highlighted and it's probably best for us to address it as part of this ticket before a merge:

- buckets for our images
When new images were uploaded and then the data was dumped it left us with a few items and profiles referencing a link to images that are now not accessible to the database. This was kind of hidden before because the data in 'development' matched the data in 'staging' but now we can clearly see that Kindly cannot access the new images.

By visiting the `studio url` link we can see that in storage there are no buckets set for the local file. So we need to find a way to get a bucket with all the images that @eagauss  uploaded to be dumped into the 'development' project and replicated in everyone's local environment.

I _presume_ there is a supabase cli command for this 🤔 

@mnixo I thought I'd tag you here too since your earlier spike really helped us settle on our current direction so if you have the capacity maybe you can help out with this new question ? @eagauss I'm aware your usual focus is automation testing but you let us know if you'd rather try out a different approach

**Comment by mnixo** [comment]
I found this: [Feature request for CLI: Seed storage files #12390](https://www.github.com/orgs/supabase/discussions/12390). Not particularly reassuring... And no suggested workarounds either.

So where do the images in the current seed file come from?? Checking the Studio URL for a locally set up supabase (with the current seed file) and checking the `images` bucket (under storage) shows that no image is actually there. I've deleted the bucket and the images still show up in the app.

This is because the images referenced in the current seed file are actually hosted elsewhere. Like [this one](https://undfcbmldjkujposixvn.supabase.co/storage/v1/object/public/images/a2ca51ad-9e1f-47a7-bc83-dad4b5252d11/684442c7-ca31-4be0-8785-85830a6f2cf2), for example. I'd assume that those are hosted on some deployed environment, which means that if the data is removed from there then it won't show up in local environments anymore.

A dirty workaround for this would be to manually update the new seed file (has 6 image URLs) to use URLs from this deployed environment. This is particularly bad because:
- Everything can still break if the data is removed from that environment.
- The workflow to update the seed file is more manual than it should be.

I can try to fiddle a little bit more with this and see if there's some other option, when I get a chance. Any ideas?

**Comment by eagauss** [comment]
@camelPhonso I have not much (if any) experience with Supabase. 
I'm still looking at the issue and if something worthwhile and relevant pops up, I'll tell you.

**Comment by camelPhonso** [comment]
thanks both @mnixo and @eagauss 

It looks like this is a shortfall of supabase at the moment so we might just need to be creative. A couple of notes:

1. @mnixo I was also seeing the issue that the items hosted in staging were showing up on my dev even though they didn't exist in the seed data, however Nich suggested this might just be about react retaining that memory and once I cleared all localstorage that was sorted. Can you please try the same and confirm if it did the trick for you?
2. we will definitely clear out all the staging data at the moment and start with a blank slate once this issue is cleared so we couldn't be relying on that anyway going forward. Which brings me to this suggestion:

💡 Maybe we can upload a couple of images to the codebase and just reference those paths in our seed

This does not replicate the behaviour of buckets but it looks like at the moment that is not an option anyway, so it would at least recreate the user experience for any visual tests and automated e2e testing on cypress.

We could store these images in the `public/` folder of our codebase - and in fact we have a few in there already we can recycle.

Does that sound like a reasonable approach or does anyone have any other suggestions?

**Comment by mnixo** [comment]
>I was also seeing the issue that the items hosted in staging were showing up on my dev even though they didn't exist in the seed data, however Nich suggested this might just be about react retaining that memory and once I cleared all localstorage that was sorted. Can you please try the same and confirm if it did the trick for you?

This one is definitely not a caching issue. Going back to [this image](https://undfcbmldjkujposixvn.supabase.co/storage/v1/object/public/images/a2ca51ad-9e1f-47a7-bc83-dad4b5252d11/684442c7-ca31-4be0-8785-85830a6f2cf2), you can find its URL in [the current seed file](https://raw.githubusercontent.com/enBloc-org/kindly/19a00ec10861752ad9b42629008241b537e873aa/supabase/seed.sql). So this works as follows:
- I populate my local Supabase instance with the current `seed.sql` file. An item is created with that image URL.
- The app fetches the data from Supabase, referencing said URL.
- The browser fetches the image from the URL. But this image is not coming from my Supabase instance, it comes from elsewhere.

>💡 Maybe we can upload a couple of images to the codebase and just reference those paths in our seed

Yes, definitely something quick and easy to manage that could be done. Once the images are pushed to the repository, their respective raw URLs can be referenced in the seed file and it should work locally (and even deployed).

I had thought about an alternative way to populate Supabase involving a script with direct calls to it, but it would be definitely more complex than the current seeding process. Now that I think about it, we'd still need to have the images pushed to repository anyway (so that they are available to the script), so there's not much to gain here 🤷

**Comment by camelPhonso** [comment]
> * I populate my local Supabase instance with the current `seed.sql` file. An item is created with that image URL.
> * The app fetches the data from Supabase, referencing said URL.
> * The browser fetches the image from the URL. But this image is not coming from my Supabase instance, it comes from elsewhere.

Ah got it! Yeah I follow, sorry I misunderstood you before. This is definitely somewhere we are referencing the staging buckets then.

> Yes, definitely something quick and easy to manage that could be done. Once the images are pushed to the repository, their respective raw URLs can be referenced in the seed file and it should work locally (and even deployed).
> 
> I had thought about an alternative way to populate Supabase involving a script with direct calls to it, but it would be definitely more complex than the current seeding process. Now that I think about it, we'd still need to have the images pushed to repository anyway (so that they are available to the script), so there's not much to gain here 🤷

Ok, I would say this is the simpler plan we have so far. @eagauss are you happy to try adding a few images to the `public/` folder and referencing them directly in the `seed.sql` file where the items are declared?

As for the issue with staged images being displayed I am fairly convinced we need to sort this in the code base, especially as Nich as pointed out to me this line in `UploadImageInput.tsx`:

```ts
const CDN =
  'https://undfcbmldjkujposixvn.supabase.co/storage/v1/object/public/images/';
```
This is some legacy code that is directly pointing at the images in our staging environment, so there may be other instances of this, or that one might be the root of our problem.

**Comment by eagauss** [comment]
@camelPhonso I added the images like `toy.jpg, books.jpg, blouse.jpg, sofa.jpg` to the `public/` folder in the project root directory.
Then I referenced them in the `supabase/seed.sql` as `/public/toy.jpg` etc. and reset the database.
Still, the images were not loaded properly.
One more thing, I cannot push changes / upload files to the repo because I have no enough permissions. 
Please have a look.

I also remember you asked me to rename the users I created from
```
donor+test.reshetniak@gmail.com
refugee+test.reshetniak@gmail.com
```
to something else but I was unable to find the conversation.

**Comment by camelPhonso** [comment]
> One more thing, I cannot push changes / upload files to the repo because I have no enough permissions. Please have a look.

Hey @eagauss that would have been because all permissions were set to the base level now that we've got the process in place for everyone to fork the repo when contributing. I've given you push permissions now to let us close this issue, just review the [contributing guidance](https://github.com/enBloc-org/kindly/blob/dev/.github/BEFORE_YOUR_FIRST_ISSUE.md#installation) when next picking a new issue please.

You should be able to push now and then we can review what's happening with the images 🤔 

> I also remember you asked me to rename the users I created from
> 
> ```
> donor+test.reshetniak@gmail.com
> refugee+test.reshetniak@gmail.com
> ```
> 
> to something else but I was unable to find the conversation.

It would have been the [notes on the PR](https://github.com/enBloc-org/kindly/pull/263#pullrequestreview-2130310868) - the address for the users is probably fine, just given them a simple username like `Test Donor`.

For the `trafalgargirls` user we should use the email `trafalgargirls@gmail.com` which is public in any case and can be in the seed data.

**Comment by eagauss** [comment]
@camelPhonso your solution worked! Now the images are being loaded 👍
<img width="533" alt="Screenshot 2024-07-14 at 16 49 09" src="https://github.com/user-attachments/assets/76f8baff-4977-4210-a073-c89a5b40395a">
<img width="908" alt="Screenshot 2024-07-14 at 16 49 19" src="https://github.com/user-attachments/assets/a0eda55a-1bb1-4fcc-8bd8-25e3d6819069">
