### ISSUE TITLE
Update state to open newly created conversation to message panel in mobile view

### ISSUE THREAD

**Issue by nichgalzin** [enBloc-org/kindly#244]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour

   When a new conversation is started in mobile version it should take you to the view of the message screen.
<img width="359" alt="Screenshot 2024-06-07 at 11 33 14" src="https://github.com/enBloc-org/kindly/assets/74174344/84805eef-02fc-4106-be7a-0facad06c76b">

# Current Behaviour

Instead to the list of conversations cards:

<img width="347" alt="Screenshot 2024-06-07 at 11 33 58" src="https://github.com/enBloc-org/kindly/assets/74174344/39880989-599e-40ca-a019-49b8d16e3f58">

## Steps to Reproduce
```
Please provide detailed steps for reproducing the issue.

1. Start a new conversation in mobile screen size
```

**Comment by YuraPetrovskyi** [comment]
Hi @nichgalzin . Do you mind if I work on this task?

**Comment by camelPhonso** [comment]
> Hi [@nichgalzin](https://github.com/nichgalzin) . Do you mind if I work on this task?

Hey @YuraPetrovskyi this issue is good to take. All yours 👌

**Comment by YuraPetrovskyi** [comment]
Hi @nichgalzin. I have some thoughts on this problem. When a new conversation is started in mobile version it should take you to the view of the message screen.  But what about when we click the message icon in the navigation bar? It seems to me that it will be better when the list of conversations cards opens. Also, when a new conversation is created, there will be a "back" arrow at the top. Here, too, not everything is so good, because the arrow can mean to return to the product page (that is, one step back), but in the project it opens a list of all conversations. Isn't it worth changing the logic a little here? 
Example:
- creating a new conversation directs to the  message screen.
- clicking the message icon takes you to the list of conversations cards.
- change the back arrow to go to all messages

**Comment by camelPhonso** [comment]
> * creating a new conversation directs to the  message screen.
> * clicking the message icon takes you to the list of conversations cards.
> * change the back arrow to go to all messages

Hey Yurii, thanks for the notes 👌 

I've just tried running this now and it looks like in the latest version of dev if we click the `/conversations` button on mobile we do go to the `ConversationsList` already, so that is all good now. 

You raise a fair point about the back arrow, but since we know that there is some redesign work going on I'd say we can leave that as is at the moment. It might be worth flagging this for Kateryna and Ben for their work, though with the research Kat shared before I suspect this has already been noted down on her end before we thought of it 😅 

I would say we focus for now on making sure the logic is all good and the user is sent to the right place when they start a new conversation, but we can leave the arrow until we get an update on the re-design and we can just make the UI change later according to the guidelines the team give us.

One thing I want to ask though - as part of your PR for this Issue can you please include a `Header.stories.ts` file showing a few different displays of the Header? (when in mobile, when in desktop, when a conversation is open in mobile, when showing the conversations list on mobile...)

There are a few `.stories.ts` files already in the code base that you can look at to get familiar with the use of that library and we've added some guidance in the [documentation ](https://github.com/enBloc-org/kindly/blob/dev/.github/TESTING.md#component-testing) and of course, you can always reach out if you have any questions 👍
